pretrained_model_path: "/nfs/turbo/coe-jjparkcv/niksrid/LAMP/checkpoints"
output_dir: "/nfs/turbo/coe-jjparkcv/niksrid/LAMP/outputs/bridge"

train_data:
  root: "/home/niksrid/mental-models/LAMP/bridge/train"
  traj_length: 16
  width: 320
  height: 240
  sample_frame_freq: 1

validation_data:
  root: "/home/niksrid/mental-models/LAMP/bridge/test"
  video_length: 16
  width: 320
  height: 240
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 30000
checkpointing_steps: 5000
validation_steps: 5000
trainable_modules:
  - "conv1d"
  - "attn1.to_q"
  - "conv_gate"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
